### ISSUE TITLE
It..... does a shit.

### ISSUE THREAD

**Issue by CasperOng** [alxb421/fake-youtube-premium#2]
![image](https://user-images.githubusercontent.com/90828938/150246870-870ca10e-0bd4-4db9-b3b3-817f07a05a60.png)
That's what happened when I have normal youtube. And there have 2 youtube premium logos if I bought a youtube premium subscription. Tested.
![image](https://user-images.githubusercontent.com/90828938/150247008-516f1b28-7cd1-4348-b5a6-7d3c01a0c831.png)

**Comment by alxb421** [comment]
Fixed in 0.2.0 version. Issue closed
